version: "3.8"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - CHOKIDAR_USEPOLLING=true
    command: ["nodemon", "-L", "src/index.js"]
    depends_on:
      - db
    restart: unless-stopped


  db: 
    image: postgres:16-alpine  # Lightweight PostgreSQL image
    container_name: postgres
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for PostgreSQL data
    ports:
      - "5432:5432"  # Map PostgreSQL container port 5432 to host port 5432

volumes:
  postgres_data:  # Define a volume for PostgreSQL persistent data
